site_name: Plannerstack documentation
site_favicon: favicon.ico

# FIXME: Somehow these pages result in a succesfull build, but a 404, couldn't understand why
#pages:
#- ['README.md', 'Introduction']
#- ['examples/autocomplete.md', 'Examples', 'Autocomplete']
#- ['examples/geocoding.md', 'Examples', 'Geocoding']
#- ['examples/geocoding.md', 'Examples', 'Results']