site_name: Plannerstack documentation
site_favicon: favicon.ico

# FIXME: Somehow these pages result in a succesfull build, but a 404, couldn't understand why
pages:
- ['README.md', 'Introduction']
- ['bliksem/Introduction.md', 'Bliksem', 'Introduction']
- ['bliksem/schedules.md', 'Bliksem', 'Schedules']
- ['bliksem/datamodel_rid.md', 'Bliksem', 'Datamodel']
- ['endpoints/bag42.md', 'Endpoints', 'Bag42']
- ['endpoints/ndov_plus.md', 'Endpoints', 'NDOV+']
- ['endpoints/planner.md', 'Endpoints', 'Planner']
- ['endpoints/premium_planner.md', 'Endpoints', 'Premium Planner']
- ['tutorials/virtual_machine_deployment.md', 'Tutorials', 'Virtual machine deployment']
- ['tutorials/osm_fix.md', 'Tutorials', 'OSM data fixes']
